### ISSUE TITLE
Player logging in with standard gear

### ISSUE THREAD

**Issue by LouDnl** [A3Wasteland/ArmA3_Wasteland.Altis#244]
On several occasions now I heard from players that they got stuck on the 'loading previous location' part. They would then get kicked from the server by a steam ticket check failed.
When logging back in they would either get stuck again on this screen or could log back in again.
When finally being able to log back in they would spawn in a standard outfit with huge backpack, rifle and no money.

**Comment by AgentRev** [comment]
Can't do nothing if they don't send in their RPT logs.

**Comment by LouDnl** [comment]
i've got one but not really anything to see. but di you have skype?

**Comment by LouDnl** [comment]
So I can send you the log

**Comment by AgentRev** [comment]
I need the RPT log directly from the game of the player that had the problem, not the server's. you can use http://gist.github.com

**Comment by LouDnl** [comment]
Here it is: https://gist.github.com/LouDnl/fb88d034e51079aa503b

**Comment by AgentRev** [comment]
I might actually need the server log. I think I got confused

**Comment by LouDnl** [comment]
Server log 15.00 - 21.00: https://gist.github.com/LouDnl/f22d514465dee8b8696e
Server log 21.00 up to about now: https://gist.github.com/LouDnl/1369147c2220cd42d247

**Comment by LouDnl** [comment]
The players name is rob3rt.
I'll get the player rpt's from a player who had this problem last night.

**Comment by AgentRev** [comment]
And the issue they experienced happened during that time period?

**Comment by LouDnl** [comment]
yes

**Comment by AgentRev** [comment]
Well there's nothing wrong in those logs, as you said... I might need the extDB logs then.

**Comment by LouDnl** [comment]
Don't know if this is related but I seem to get this error in my server RPT every once in a while:

22:49:22 Error in expression <ect 2 } else { objNull };

if !(_killer isKindOf "Man") then { _killer = effecti>
22:49:22   Error position: <isKindOf "Man") then { _killer = effecti>
22:49:22   Error Generic error in expression
22:49:22 File mpmissions\ArmA3_Wasteland_v1_NLU.Altis\server\functions\serverPlayerDied.sqf, line 25
22:49:22 Error in expression <ect 2 } else { objNull };

if !(_killer isKindOf "Man") then { _killer = effecti>
22:49:22   Error position: <isKindOf "Man") then { _killer = effecti>
22:49:22   Error Generic error in expression
22:49:22 File mpmissions\ArmA3_Wasteland_v1_NLU.Altis\server\functions\serverPlayerDied.sqf, line 25

**Comment by LouDnl** [comment]
I checked the logs again. All I can see is msgs not being sent and received and some netmsg errors. Could it be that the connection from client to server wasn't good so the player couldnt load in and when finally connected reset the character?

**Comment by LouDnl** [comment]
Ok so I have a player log from the time this happened.
Chat says he encountered the problem around 13:15 ~ 13:35

(2165 ) 13:31:51 : Global: [TIL] WarmasterStuvis: wtf? anyone have any problems when they logged in today?
(2169 ) 13:32:18 : Global: [TIL] WarmasterStuvis: all my gear has changed
(2179 ) 13:32:59 : Global: [TIL] WarmasterStuvis: i logged in fine but all my gear i logged out with this morning has changed

player rpt log: https://gist.github.com/LouDnl/880115269a4da0492af5

**Comment by AgentRev** [comment]
When this happens, I need player RPT, server RPT, and extDB log, all at the same time.

**Comment by AgentRev** [comment]
Maybe it could be an error at the moment of saving too

**Comment by LouDnl** [comment]
Here is the server RPT from around that time: https://gist.github.com/LouDnl/387c4ab1e7300467bc3f
And here are the extDB logs from around that time: https://gist.github.com/LouDnl/98e19a8f2043178595bd

**Comment by AgentRev** [comment]
I would say wait till the next update, I have already fixed extDB constraint errors, maybe that could be related to it.

**Comment by LouDnl** [comment]
Will do, can't wait :)

**Comment by LouDnl** [comment]
Still have this sometimes. Even have player spawn npc's walking around sometimes as if the connection between the player and the spawn npc was disconnecten.
Last weekend I was ingame, but my son logged in on my laptop. He started Arma and because you cannot run the same copy of Arma on 2 pc's I got kicked from the game. But my character stayed ingame and turned into an NPC. I logged back in and he was still there. When I killed him he respawned on spawn island and started swimming towards my group leader.
I have to use deleteobject or disablesimulation to stop the npc.

**Comment by LouDnl** [comment]
Still is still an issue. Players get their bank account reset in the process aswell. I will turn on SQL logging for extDB.

**Comment by LouDnl** [comment]
Here's a server RPT where a player had this happen. The players UID is: 76561198056812490
And the gist link: https://gist.github.com/LouDnl/eaacefb52b84b0b8f872
This seems to be happening quite often lately.
No errors in the extDB log.

**Comment by AgentRev** [comment]
The problem must be on the client, I need the client RPT log

**Comment by LouDnl** [comment]
Allright I will try and get that. I've had this happen to multiple players over the last months. It's totally random. But it usually also comes with resetting of bankmoney aswell.

**Comment by LouDnl** [comment]
Well this guy had -noLogs haha. Will come back when it happens again.

**Comment by AgentRev** [comment]
noLogs = noHelp

**Comment by LouDnl** [comment]
I'll keep the extDB debug on untill I get a server RPT and client RPT. Will report back sir :+1:

**Comment by LouDnl** [comment]
Just had a player login with standard gear again. Had full sniper gear when he logged in. But when he logged out earlier today he had different gear. He did however spawn in the location he logged out.

Player UID: 76561198045856719
Client RPT: https://gist.github.com/LouDnl/40eaa5d7b1e721802456
Server RPT: https://gist.githubusercontent.com/LouDnl/ed5bf69f04c41440c5ed/raw/gistfile1.txt
extDB: https://gist.github.com/LouDnl/c322b17ef95e8c737694

**Comment by LouDnl** [comment]
When he logged in he was in the location he logged out, but had the different gear. What i did was ask him to respawn and then go to the lobby and then back in game. He didn't have any bank money but with other players we experienced their bank money reset when they log in and have standard gear.

**Comment by LouDnl** [comment]
Had another player with the same problem yesterday. This was round 16.45. His gear was reset and his bank money aswell.
Player UID: 76561198035264399
Client RPT: https://gist.github.com/LouDnl/ae29384a76ecfb2c6f31
Server RPT: http://we.tl/ZXofn1MvnU (too big for Gist, about 30Mb)
extDB: https://gist.github.com/LouDnl/1ec6e68709edcf060f09

**Comment by LouDnl** [comment]
It also seems to happen when players are logging into the game. After they select a class in the lobby and get a steam ticket failed when loading their character. This is however not what happend the other times.

**Comment by JoSchaap** [comment]
the extdb log starts at 17:13 if the error occurred at 16:45 you've sent the wrong file :)

**Comment by LouDnl** [comment]
ExtDB log prior to that shows exactly the same information. I posted two accounts of this problem.
https://gist.github.com/LouDnl/93d7dc241b5668935418

**Comment by LouDnl** [comment]
It seems to be connected to players with connection issues. It doesn't happen very much. But when people have connection issues when loading into the game.

**Comment by LouDnl** [comment]
Still having this with extDB2.

**Comment by LouDnl** [comment]
I'll be updating both my live servers to the newest a3wasteland.ini and commits including extDB2 v49 debug version.
When  I have logs I will contact you here Rev.

**Comment by LouDnl** [comment]
Here's a new log:
https://drive.google.com/file/d/0By5PInQAIAA6OXZtVF9HMWNBTmM/view?usp=sharing
client logs, server logs, extDB logs.
Client UID: 76561197978639089

Don't mind the '2015/04/09, 21:20:12 Server: Network message aad2a7 is pending' errors in the large server RPT. I'm having problems since 1.42 and this has nothing to do with the error that was there prior to 1.42.

**Comment by LouDnl** [comment]
I forgot to mention, player 76561197978639089 logged in invisible so I advised him to go to the lobby and then back in. Then he spawned in at (2015/04/09, 21:24:38) with default arma gear. He didn't lose his bank money though.

**Comment by AgentRev** [comment]
Okay, from the log it says that the default gear seems to have been saved either right before or right after he logged off and before he logged in back... which is quite fucked up. This might have to do with the spawn island ghost bug mixed an engine issue with HandleDisconnect, but I really have no idea. The more info is collected, the more abstract it gets.

**Comment by AgentRev** [comment]
Yep pretty sure it has to do with the player corpse respawning as AI before HandleDisconnected is triggered. As to why is it happening, or how to prevent it, I'm not sure. I was gonna say mark players as unfit for saving until their client confirms they're good to go, but in this case I suspect the client is already gone by the time the player respawns as AI, and server-side respawn events are very, very unreliable. This is a thought one.

**Comment by LouDnl** [comment]
I'll try to collect more logs.

**Comment by AgentRev** [comment]
For the moment it won't serve much purpose, we'd need to add a couple more logging lines in the scripts to extract more relevant information, like the time at which HandleDisconnect and onPlayerDisconnected runs.

**Comment by AgentRev** [comment]
You don't need to collect client logs anymore until further notice

**Comment by LouDnl** [comment]
Ok. So it seems everything is interconnected.
- Players logging out leaving an AI with their gear.
- Players logging in invisible.
- Players logging in in default arma gear.
- Players logging in in default arma gear and bankmoney reset.
- Players getting stuck on black screen (loading/applying player data) after class selection screen.

**Comment by LouDnl** [comment]
So you don't need anymore logs right?

**Comment by AgentRev** [comment]
Not at the moment.

**Comment by LouDnl** [comment]
I've implemented your new commits with the extra logging. Send you the server side logs as soon as someone experience the problem?

**Comment by LouDnl** [comment]
Was using your new logging and already have a player logging in with default gear. Here are the extDB logs and server RPT's from before and after the server restart. He logged out before and logged back in after. His UID is: 76561198144993692
https://drive.google.com/file/d/0By5PInQAIAA6dGRiX2hCVW14bE0/view?usp=sharing

**Comment by LouDnl** [comment]
Will be testing your newest commits after our next restart.

**Comment by ancientevil** [comment]
having the same issue now and then. It occurs once every 1 or 2 weeks.

**Comment by LouDnl** [comment]
Still having this problem, even with the fix you tried to make.
Had someone logging in with default arma gear again. This time within the same playing session (no restart of server).
https://drive.google.com/file/d/0By5PInQAIAA6UEM2b3NGU0ZwWHc/view?usp=sharing

**Comment by AgentRev** [comment]
Same problem as before, standard gear is saved on disconnect for some unknown reason.

Also, did he lose his bank money? The amount went from 116,073 to 0 in less than a minute.

**Comment by LouDnl** [comment]
Yes he lost his bank money and spawned in with standard gear.

**Comment by AgentRev** [comment]
Alright, the bank money reset happened 12 minutes before disconnection, so it could be a separate problem. Unless both issues are related to network bugs or something.

**Comment by LouDnl** [comment]
Maybe the loss of bankmoney triggers something?

**Comment by AgentRev** [comment]
No, that would probably be "a greater problem is causing both bank money to fail saving and standard gear to overwrite the player save"

**Comment by LouDnl** [comment]
Maybe he whent to the spawn menu to be afk? He's not online anymore so I can't ask him.

**Comment by AgentRev** [comment]
I've been analyzing his data, and here's what I pieced up so far:

> 21:39:13 - Player connected
> 21:39:18 - Bank money loaded = 113573; PlayerSave not found, new spawn
> 21:39:45 - Player saved in Negades; Bank = 113573 Wallet = 2500
> 21:40:22 - Player saved in Negades; Bank = 113573 Wallet = 2500
> 21:41:21 - Player money saved; Bank = 116073; Wallet = 0
> 21:41:36 - Player saved in Negades near ATM; Bank = 116073; Wallet = 0
> 21:41:40 - Player disconnected; Player inventory saved via HandleDisconnect
> 21:41:59 - Player connected
> 21:42:01 - Bank money loaded = 116073; Previous PlayerSave loaded in front of ATM
> 21:42:11 - Player saved in Negades near ATM; <b>Bank = 116073</b>; Wallet = 0
> [Possible unrecorded death/respawn]
> 21:43:07 - Player saved in Agios Dionysios, 4 km east of Negades; <b>Bank = 0</b>; Wallet = 2500
> 21:44:04 - Player saved in Agios Dionysios; Bank = 0; Wallet = 2500
> 21:44:56 - Player save deleted, likely due to death
> 21:46:45 - Player saved in Agios Dionysios; Bank = 0; Wallet = 2500
> 21:47:05 - Player saved in Agios Dionysios; Bank = 0; Wallet = 2500
> 21:48:05 - Player saved in Agios Dionysios; Bank = 0; Wallet = 2500
> 21:49:05 - Player saved in Agios Dionysios; Bank = 0; Wallet = 2500
> 21:49:43 - Player save deleted, likely due to death
> 21:50:37 - Player saved in Telos; Bank = 0; Wallet = 2500
> 21:51:06 - Player saved in Telos; Bank = 0; Wallet = 2500
> 21:52:05 - Player saved in Telos; Bank = 0; Wallet = 2500
> 21:53:05 - Player saved near Telos; Bank = 0; Wallet = 2500
> 21:54:25 - Player saved near Anthrakia; Bank = 0; Wallet = 2500
> 21:55:15 - Player disconnected; <b>Standard gear</b> saved via HandleDisconnect

**Comment by LouDnl** [comment]
Can I do anything for you to find the problem better? Need more logs?

**Comment by LouDnl** [comment]
Do you still want me to log? Or can I change back to non debug extDB2 files?

**Comment by AgentRev** [comment]
I don't have any more time to look into this until my semester is complete, at the end of May.

**Comment by LouDnl** [comment]
Ok we'll have to wait then :)

**Comment by AgentRev** [comment]
I may have an idea to fix the standard gear problem, although I don't know if it will also fix bank reset. So, the idea would be to add an init field to all the player units in mission.sqm, so that a "Respawn" event is assigned to them server-side, as to be able to track respawns without relying exclusively on client data, which I think is the cause of gear reset. I will do some experiments to check the viability.

**Comment by LouDnl** [comment]
I upvoted it and asked if Dwarden would please get it assigned.

**Comment by LouDnl** [comment]
Dwarden asks if you can check if this bug you reported still exists in the current latest RC version.

**Comment by AgentRev** [comment]
Nice! Will implement the fix once it's brought to the stable branch. Again, I don't know if it's gonna fix the bank reset, but in theory it should allow me to prevent the standard gear issue.

**Comment by LouDnl** [comment]
Have you tested it yet? Thats what Dwarden asks. To see if its still there in RC. The bug u reported.

Verstuurd vanaf mijn iPhone

Op 4 jun. 2015 om 19:01 heeft Agent Revolution <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Nice! Will implement the fix once it's brought to the stable branch. Again, I don't know if it's gonna fix the bank reset, but in theory it should allow me to prevent the standard gear issue.

-

**Comment by AgentRev** [comment]
I don't know, I don't switch to RC anymore because it messes up my files like half of the time. If the fix I suggested was implemented then normally it will fix the problem without a doubt.

**Comment by LouDnl** [comment]
No he didn’t say it was implemented. Dwarden asked if we could test if it was fixed.

**Comment by ancientevil** [comment]
We havent heard anymore more problems on our DADS #1 server. Running latest perfbuild from BIS dropbox.

**Comment by LouDnl** [comment]
Would be nice if you could test on RC.

Player count on my server has dropped, but still hearing about this bug.

**Comment by AgentRev** [comment]
Tested on RC, still present.

**Comment by LouDnl** [comment]
Ok thanks. Will let Dwarden know.

**Comment by LouDnl** [comment]
Unfortunatly still getting players where bank accounts are reset. 
This time the player died and disconnected when he was in the respawn menu.

RPT and extDB log: http://arma.nl-united.nl/logs.7z

RPT log shows this:
2015/07/08, 14:49:25 "onPlayerDisconnected - ["Tommy","76561198085099283"]"
2015/07/08, 14:49:25 Client: Remote object 11:0 not found
2015/07/08, 14:49:25 "HandleDisconnect - ["Tommy","76561198085099283"] - alive: true - local: true"

extDB log shows this:
[14:49:02:087 +02:00] [Thread 3280] extDB2: Extension Input from Server: 1:364272:deletePlayerSave:76561198085099283:1
[14:49:02:087 +02:00] [Thread 3280] extDB2: Extension Output to Server: [1]
[14:49:02:087 +02:00] [Thread 3004] extDB2: SQL_CUSTOM_V2: Trace: UniqueID: 1 Input: deletePlayerSave:76561198085099283:1

Need any other logs?

**Comment by LouDnl** [comment]
Wait I only the logs from before the disconnect I see. 
Download these too: http://arma.nl-united.nl/logs2.7z

When he reconnected his bank money was still there. It dissapeared during connect I think?

extDB:

[19:28:10:014 +02:00] [Thread 5092] extDB2: Extension Input from Server: 1:258305:insertOrUpdatePlayerInfo:76561198085099283:BankMoney=2535332:BankMoney=VALUES(BankMoney)
[19:28:10:014 +02:00] [Thread 5092] extDB2: Extension Output to Server: [1]
[19:28:10:014 +02:00] [Thread 3920] extDB2: SQL_CUSTOM_V2: Trace: UniqueID: 1 Input: insertOrUpdatePlayerInfo:76561198085099283:BankMoney=2535332:BankMoney=VALUES(BankMoney)
[19:28:10:014 +02:00] [Thread 5092] extDB2: Extension Input from Server: 1:258305:insertOrUpdatePlayerSave:76561198085099283:1:1:Thirst=99.277855:Thirst=VALUES(Thirst)
[19:28:10:014 +02:00] [Thread 5092] extDB2: Extension Output to Server: [1]
[19:28:10:014 +02:00] [Thread 4732] extDB2: SQL_CUSTOM_V2: Trace: UniqueID: 1 Input: insertOrUpdatePlayerSave:76561198085099283:1:1:Thirst=99.277855:Thirst=VALUES(Thirst)

[19:28:51:235 +02:00] [Thread 5092] extDB2: Extension Input from Server: 1:258305:insertOrUpdatePlayerInfo:76561198085099283:BankMoney=0:BankMoney=VALUES(BankMoney)
[19:28:51:236 +02:00] [Thread 5092] extDB2: Extension Output to Server: [1]
[19:28:51:236 +02:00] [Thread 3920] extDB2: SQL_CUSTOM_V2: Trace: UniqueID: 1 Input: insertOrUpdatePlayerInfo:76561198085099283:BankMoney=0:BankMoney=VALUES(BankMoney)
[19:28:51:237 +02:00] [Thread 3920] extDB2: SQL_CUSTOM_V2: Trace: UniqueID: 1 Result: [1,[]]
[19:28:51:300 +02:00] [Thread 5092] extDB2: Extension Input from Server: 1:258305:insertOrUpdatePlayerSave:76561198085099283:1:1:Hunger=100,Thirst=100,Position='["4105.458496","13797.391602","0.0014534"]',Direction=143.419098,Stance='"Pknl"',Backpack='"B_AssaultPack_blk"',WastelandItems='[["cannedfood",2],["water",2],["repairkit",2]]':Hunger=VALUES(Hunger),Thirst=VALUES(Thirst),Position=VALUES(Position),Direction=VALUES(Direction),Stance=VALUES(Stance),Backpack=VALUES(Backpack),WastelandItems=VALUES(WastelandItems)
[19:28:51:300 +02:00] [Thread 5092] extDB2: Extension Output to Server: [1]
[19:28:51:300 +02:00] [Thread 3920] extDB2: SQL_CUSTOM_V2: Trace: UniqueID: 1 Input: insertOrUpdatePlayerSave:76561198085099283:1:1:Hunger=100,Thirst=100,Position='["4105.458496","13797.391602","0.0014534"]',Direction=143.419098,Stance='"Pknl"',Backpack='"B_AssaultPack_blk"',WastelandItems='[["cannedfood",2],["water",2],["repairkit",2]]':Hunger=VALUES(Hunger),Thirst=VALUES(Thirst),Position=VALUES(Position),Direction=VALUES(Direction),Stance=VALUES(Stance),Backpack=VALUES(Backpack),WastelandItems=VALUES(WastelandItems)

**Comment by AgentRev** [comment]
Both links 404'd

**Comment by LouDnl** [comment]
I see that my idiot self deleted the files. Here's a new zip with all of them in: http://arma.nl-united.nl/logs.7z

**Comment by LouDnl** [comment]
Still an issue unfortunatly.

**Comment by AgentRev** [comment]
Which one? or both?

**Comment by LouDnl** [comment]
Heard the bank reset less frequent. But the logging in with default gear still happens quite often. Both sometimes start with being invisible or being unable to move.

**Comment by AgentRev** [comment]
Waitaminit... I think I know how to solve default gear... On [this](https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/blob/a6d06946616920d6d31eb89eb3a156923aa30e94/server/init.sqf#L35) line, try changing

    !(_unit getVariable ["playerSpawning", false])

to

    !(_unit getVariable ["playerSpawning", true])

Default gear is normally caused by a botched respawn that misfired on player disconnect. If `playerSpawning` is not initialized on the botched unit, in theory this would fix the problem!

**Comment by LouDnl** [comment]
Will try that and update both servers with it :+1:

**Comment by LouDnl** [comment]
Here we go :)
https://github.com/LouDnl/ArmA3_Wasteland.Altis/commit/471402420761fb5d4593dcfbc45b194d7b4701c7

**Comment by AgentRev** [comment]
About bank money, did you get any report since the last fix? (e7efbf8d74f0ac51158fd509689f0de3f03e9aaa)

**Comment by LouDnl** [comment]
1 or 2 maybe, but could be false positives. Will keep an eye out for it.

**Comment by AgentRev** [comment]
Any new reports, or is everything fine so far?

**Comment by LouDnl** [comment]
None yet. But our servers have been down a lot the pas week and a half due to ddos attacks.
